[package]
name = "cubiomes"
version = "0.1.1"
edition = "2021"
authors = ["Ville Kujala"]
description = "A safe rust wrapper for the cubiome library"
license = "MIT"
keywords = ["minecraft", "minecraft-worldgen"]
categories = ["api-bindings"]

[features]
default = ["cc_build"]
cc_build = ["cubiomes-sys/cc_build"]

[dependencies]
thiserror = "2.0"
bitflags = "2.0"
cubiomes-sys = { path = "../cubiomes-sys", default-features = false }
