name: rustfmt

on:
  - push
  - pull_request

jobs:
  fmt:
    runs-on: ubuntu-latest

    steps:
    - name: Install nightly toolchain
      run: | 
        rustup toolchain install nightly
        rustup component add --toolchain nightly-x86_64-unknown-linux-gnu rustfmt
    - name: Checkout
      uses: actions/checkout@v4
    - name: check formatting
      run: cargo +nightly fmt -- --check
